#!/usr/bin/env python3
"""Aggregate the run reports into reports/summary.json and VALIDATION_RESULTS.md.

Every figure is read from the report files. Nothing is asserted independently of
them: an earlier version of this tooling wrote "Criterion H PASS" as a literal,
which is how the document came to contradict its own data.

Usage:
    python3 scripts/generate_summary.py
"""

import json
import sys
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = ROOT / "reports"
DOC_PATH = ROOT / "VALIDATION_RESULTS.md"

REPORT_FILES = [
    ("run_1_1min.json", "1 minute"),
    ("run_2_2min.json", "2 minutes"),
    ("run_3_4min.json", "4 minutes"),
    ("run_4_6min.json", "6 minutes"),
]


def load_reports() -> List[Dict[str, Any]]:
    reports = []
    for filename, label in REPORT_FILES:
        path = REPORTS_DIR / filename
        if not path.exists():
            print(f"missing {path.relative_to(ROOT)}", file=sys.stderr)
            continue
        data = json.loads(path.read_text())
        data["_label"] = label
        data["_file"] = filename
        reports.append(data)
    return reports


def overall(reports: List[Dict[str, Any]], criterion: str) -> str:
    verdicts = {r.get(criterion, {}).get("verdict", "NO EVIDENCE") for r in reports}
    if "FAIL" in verdicts:
        return "FAIL"
    if verdicts == {"PASS"}:
        return "PASS"
    return "NO EVIDENCE"


def build_markdown(reports: List[Dict[str, Any]]) -> str:
    lines: List[str] = []
    add = lines.append

    add("# Validation Results")
    add("")
    add(
        "Generated by `scripts/generate_summary.py` from the JSON files in "
        "`reports/`. Every number below comes from those files."
    )
    add("")

    add("## Runs")
    add("")
    add("| Run | Duration | Status | Scenarios passed | Checks passed | Failed | Skipped |")
    add("|-----|----------|--------|------------------|---------------|--------|---------|")
    for r in reports:
        summary = r.get("scenario_summary", {})
        checks = r.get("checks", {})
        add(
            f"| {r.get('sequence', '?')} | {r['_label']} | {r.get('status', '?')} | "
            f"{summary.get('scenarios_passed', '?')}/{summary.get('total_scenarios', '?')} | "
            f"{checks.get('passed', '?')} | {checks.get('failed', '?')} | "
            f"{checks.get('skipped', '?')} |"
        )
    add("")

    add("## Success criteria")
    add("")
    g = overall(reports, "criterion_g_audit")
    h = overall(reports, "criterion_h_isolation")
    add(f"- **Criterion G — audit completeness: {g}**")
    for r in reports:
        c = r.get("criterion_g_audit", {})
        add(
            f"  - {r['_label']}: {c.get('verdict', '?')} "
            f"({c.get('passed', 0)} passed, {c.get('failed', 0)} failed)"
        )
    add(f"- **Criterion H — user isolation: {h}**")
    for r in reports:
        c = r.get("criterion_h_isolation", {})
        add(
            f"  - {r['_label']}: {c.get('verdict', '?')} "
            f"({c.get('passed', 0)} passed, {c.get('failed', 0)} failed)"
        )
    add("")

    add("## Cross-validation")
    add("")
    for r in reports:
        add(f"- {r['_label']}: {r.get('cross_validation_errors', '?')} disagreements")
    add("")

    add("## Extraction coverage")
    add("")
    add(
        "The engine's extractor returns no fact for a large share of utterances, "
        "and is not deterministic across identical inputs. Presence checks skip "
        "those utterances rather than reporting a storage failure, so the skipped "
        "column above is mostly this."
    )
    add("")
    add("| Run | Utterances played | Yielded no fact |")
    add("|-----|-------------------|-----------------|")
    for r in reports:
        gaps = r.get("extraction_gaps", {})
        add(
            f"| {r['_label']} | {gaps.get('utterances_played', '?')} | "
            f"{gaps.get('utterances_yielding_no_fact', '?')} |"
        )
    add("")

    return "\n".join(lines) + "\n"


def main() -> int:
    reports = load_reports()
    if not reports:
        print("no reports found", file=sys.stderr)
        return 1

    summary = {
        "runs": [
            {
                "sequence": r.get("sequence"),
                "run_number": r.get("run_number"),
                "duration_seconds": r.get("duration_seconds"),
                "status": r.get("status"),
                "scenario_summary": r.get("scenario_summary"),
                "checks": r.get("checks"),
                "criterion_g_audit": r.get("criterion_g_audit"),
                "criterion_h_isolation": r.get("criterion_h_isolation"),
                "cross_validation_errors": r.get("cross_validation_errors"),
                "extraction_gaps": r.get("extraction_gaps"),
            }
            for r in reports
        ],
        "criterion_g_audit": overall(reports, "criterion_g_audit"),
        "criterion_h_isolation": overall(reports, "criterion_h_isolation"),
    }
    (REPORTS_DIR / "summary.json").write_text(json.dumps(summary, indent=2))
    DOC_PATH.write_text(build_markdown(reports))
    print(f"wrote {Path('reports/summary.json')} and {DOC_PATH.name}")
    print(f"criterion G: {summary['criterion_g_audit']}")
    print(f"criterion H: {summary['criterion_h_isolation']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
