#!/usr/bin/env python3
"""Render docs/CHECKER_AB_RESULTS.md from reports/checker_bug_ab.json.

Every figure is read from the report file. Nothing is asserted independently of
it, which is the whole point of the exercise being documented.

Usage:
    python3 scripts/generate_ab_table.py [--report reports/checker_bug_ab.json]
                                         [--out docs/CHECKER_AB_RESULTS.md]
"""

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REPORT = ROOT / "reports" / "checker_bug_ab.json"
DEFAULT_OUT = ROOT / "docs" / "CHECKER_AB_RESULTS.md"

ARM_LABELS = {
    "baseline": "baseline (current checker)",
    "baseline_repeat": "baseline, repeated last",
    "all_harness_faults": "every harness fault at once",
}


def _signed(value: Optional[int]) -> str:
    if value is None:
        return "—"
    return f"{value:+d}" if value else "0"


def _arm_label(arm: Dict[str, Any]) -> str:
    return ARM_LABELS.get(arm["arm"], f"`{arm['arm']}`")


def build(
    report: Dict[str, Any],
    report_path: str = "reports/checker_bug_ab.json",
    title: str = "Checker A/B — what the pre-fix harness was measuring",
) -> str:
    lines: List[str] = []
    add = lines.append

    arms = [a for a in report["arms"] if "checks" in a]
    baseline = next((a for a in arms if a["arm"] == "baseline"), None)
    repeat = next((a for a in arms if a["arm"] == "baseline_repeat"), None)

    add(f"# {title}")
    add("")
    add(
        "Generated by `scripts/generate_ab_table.py` from "
        f"`{report_path}`. Every number comes from that file."
    )
    add("")
    engine_ttl = report["engine"].get("operator_declared_profile_cache_ttl_seconds")
    ttl_clause = (
        f" That engine process was started with "
        f"`PROFILE_CACHE_TTL_SECONDS={engine_ttl:g}`, declared by the operator "
        "because this script cannot read the value from the engine."
        if isinstance(engine_ttl, (int, float))
        else ""
    )
    add(
        f"The same {report['scenarios']['count']} scenarios (seed "
        f"{report['scenarios']['seed']}) were played "
        f"{len(arms)} times against the same running engine at "
        f"`{report['engine']['base_url']}`, for "
        f"{report['duration_seconds']}s each. The engine was not restarted, "
        "rebuilt or reconfigured between arms. The only thing that changed is "
        f"which pre-fix measurement fault the checker was running with.{ttl_clause}"
    )
    add("")

    add("## Every arm")
    add("")
    declared_ttl = report["engine"].get("operator_declared_profile_cache_ttl_seconds")
    add(
        "| Arm | Harness-assumed cache TTL | Scenarios passed | Checks passed | "
        "Failed | Skipped | Cross-validation errors | Criterion G | Criterion H |"
    )
    add("| --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    for arm in arms:
        summary = arm["scenario_summary"]
        checks = arm["checks"]
        ttl = arm.get("harness_assumed_profile_cache_ttl_seconds")
        ttl_cell = f"{ttl:g}s" if isinstance(ttl, (int, float)) else "—"
        add(
            f"| {_arm_label(arm)} | {ttl_cell} "
            f"| {summary['scenarios_passed']}/{summary['total_scenarios']} "
            f"| {checks['passed']} | {checks['failed']} | {checks['skipped']} "
            f"| {arm['cross_validation_errors']} "
            f"| {arm['criterion_g_audit']['verdict']} "
            f"| {arm['criterion_h_isolation']['verdict']} |"
        )
    add("")
    if declared_ttl is not None:
        add(
            f"The engine process behind every arm above was reported by the "
            f"operator as running with `PROFILE_CACHE_TTL_SECONDS={declared_ttl:g}`. "
            "The TTL column is what the *harness* planned the run's cache "
            "expectations against, which is a separate thing: the pre-fix state "
            "had both at 3600s."
        )
        add("")

    failing = [a for a in arms if a.get("failed_outcomes")]
    if failing:
        add("## Which checks failed, by name")
        add("")
        add("| Arm | Failed outcomes |")
        add("| --- | --- |")
        for arm in failing:
            named = ", ".join(
                f"`{outcome}` x{count}"
                for outcome, count in sorted(
                    arm["failed_outcomes"].items(), key=lambda kv: -kv[1]
                )
            )
            add(f"| {_arm_label(arm)} | {named} |")
        add("")
        add(
            "`fact_retrievable` failures track the extractor, which is "
            "non-deterministic across identical inputs, so a small count there "
            "moves between runs on its own and should not be read as a fault's "
            "effect."
        )
        add("")

    if baseline and repeat:
        delta = (
            repeat["scenario_summary"]["scenarios_passed"]
            - baseline["scenario_summary"]["scenarios_passed"]
        )
        add(
            f"The baseline ran first and last. Between those two runs the "
            f"scenario count moved by {delta:+d} and failed checks by "
            f"{repeat['checks']['failed'] - baseline['checks']['failed']:+d}, "
            "which is the run-to-run spread every per-fault delta below has to "
            "clear to mean anything."
        )
        add("")

    add("## Per fault")
    add("")
    add(
        "Each row is one fault enabled alone, against the baseline. A negative "
        "scenario delta and a positive failed-check delta mean the fault "
        "manufactured failures out of an engine that had not changed."
    )
    add("")
    add(
        "| Fault | Fixed in | Scenarios passed | Δ scenarios | Δ checks failed "
        "| Δ checks skipped | Δ cross-validation errors |"
    )
    add("| --- | --- | --- | --- | --- | --- | --- |")
    for row in report.get("attribution", []):
        commits = ", ".join(f"`{c}`" for c in row["commits"]) or "—"
        name = ARM_LABELS.get(row["arm"], f"`{row['arm']}`")
        add(
            f"| {name} | {commits} "
            f"| {row['scenarios_passed']} "
            f"| {_signed(row['scenarios_passed_delta'])} "
            f"| {_signed(row['checks_failed_delta'])} "
            f"| {_signed(row['checks_skipped_delta'])} "
            f"| {_signed(row['cross_validation_errors_delta'])} |"
        )
    add("")

    baseline_failed = set((baseline or {}).get("failed_outcomes") or {})
    harmless = [
        row
        for row in report.get("attribution", [])
        if len(row["faults"]) == 1
        and row["checks_failed_delta"] is not None
        and row["checks_failed_delta"] <= 0
    ]
    if harmless:
        add("### Faults that did not manufacture failures in this run")
        add("")
        for row in harmless:
            arm = next(a for a in arms if a["arm"] == row["arm"])
            unique = sorted(set(arm.get("failed_outcomes") or {}) - baseline_failed)
            unique_text = (
                "outcomes failing here and not in the baseline: "
                + ", ".join(f"`{o}`" for o in unique)
                if unique
                else "no outcome failed here that did not also fail in the baseline"
            )
            add(
                f"- **`{row['faults'][0]}`** — Δ failed checks "
                f"{_signed(row['checks_failed_delta'])}, so on this run it did not "
                f"turn a working engine into a failing report; {unique_text}."
            )
        add("")

    add("## What each fault was")
    add("")
    for row in report.get("attribution", []):
        if len(row["faults"]) != 1:
            continue
        add(f"- **`{row['faults'][0]}`** (fixed in {', '.join(row['commits'])}) — "
            f"{row['descriptions'][0]}")
    add("")

    excluded = report.get("excluded_faults") or {}
    if excluded:
        add("## Not measured here")
        add("")
        for fault, reason in excluded.items():
            add(f"- **`{fault}`** — {reason}")
        add("")
        declared = report["engine"].get(
            "operator_declared_profile_cache_ttl_seconds"
        )
        add(
            "The engine in these runs was reported by the operator as using a "
            f"profile cache TTL of {declared}s. This script cannot read that "
            "value from the engine, so it is recorded as declared, not measured."
        )
        add("")

    literal_arms = [
        a for a in arms if "report_writer_would_have_published" in a
    ]
    if literal_arms:
        add("## What the pre-fix report writer would have published")
        add("")
        add(
            "The last two faults were in the report writer rather than in any "
            "check, so their effect is not a delta — it is a verdict that "
            "ignores the checks underneath it."
        )
        add("")
        for arm in literal_arms:
            published = arm["report_writer_would_have_published"]
            g, h = published["criterion_g_audit"], published["criterion_h_isolation"]
            add(
                f"On the `{arm['arm']}` arm the old writer would have published "
                f"criterion H as **{h['verdict']}** with "
                f"`isolation_pass_rate: {h['isolation_pass_rate']}`, while the "
                f"checks it overrode found {h['passed']} passed and "
                f"{h['failed']} failed. Criterion G would have been "
                f"**{g['verdict']}** on the basis `{g['basis']}`."
            )
            add("")

    add("## Reproducing this")
    add("")
    arm_names = ",".join(a["arm"] for a in report["arms"])
    default_arms = {
        "baseline",
        "baseline_repeat",
        "all_harness_faults",
        *[a for a in ARM_LABELS],
    }
    add("```bash")
    add("# the engine must be running")
    if isinstance(engine_ttl, (int, float)) and engine_ttl != 30:
        add(f"#   started with PROFILE_CACHE_TTL_SECONDS={engine_ttl:g}")
    command = f"python3 scripts/run_checker_ab.py --duration {report['duration_seconds']}"
    if len(report["arms"]) < 9:
        command += f" \\\n    --arms {arm_names}"
    if isinstance(engine_ttl, (int, float)):
        command += f" \\\n    --engine-profile-cache-ttl {engine_ttl:g}"
    if len(report["arms"]) < 9:
        command += f" \\\n    --out {report_path}"
    add(command)
    doc_command = "python3 scripts/generate_ab_table.py"
    if report_path != "reports/checker_bug_ab.json":
        doc_command += f" --report {report_path} --out <doc>"
    add(doc_command)
    add("```")
    add("")
    if any("reuse_run_number" in a["faults"] for a in report["arms"]):
        add(
            "The `reuse_run_number` arm writes its events against `run_number=1` "
            "in `audit_log.db`, which is exactly the fault it reproduces, so that "
            "arm's numbers depend on how much history that run number already "
            "holds. Every other arm allocates a fresh run number."
        )
        add("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", default=str(DEFAULT_REPORT))
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument("--title", default=None, help="document H1")
    args = parser.parse_args()

    report_path = Path(args.report)
    if not report_path.exists():
        print(f"missing {report_path}; run scripts/run_checker_ab.py first")
        return 1

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    try:
        relative = str(report_path.resolve().relative_to(ROOT))
    except ValueError:
        relative = str(report_path)
    out.write_text(
        build(
            json.loads(report_path.read_text()),
            report_path=relative,
            **({"title": args.title} if args.title else {}),
        )
    )
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
